### ISSUE TITLE
Unable to run multiple RStudio Server sessions at the same time

### ISSUE THREAD

**Issue by nickjer** [OSC/bc_osc_rstudio_server#1]
This could be due to both sessions sharing a common directory `~/.rstudio`. Will need to look into modifying this through an `rsession.conf` with maybe the option `session-default-working-dir` and `session-default-new-project-dir`.

**Comment by nickjer** [comment]
Found this useful article explaining the state saved/read for an R session:

https://support.rstudio.com/hc/en-us/articles/218730228-Resetting-a-user-s-state-on-RStudio-Server

**Comment by nickjer** [comment]
Seems neither of those options affect the location of `~/.rstudio`. It looks like it is hardcoded into the code.

https://github.com/rstudio/rstudio/blob/54cd3abcfc58837b433464c793fe9b03a87f0bb4/src/cpp/core/r_util/RUserData.cpp#L42-L47

Only trick I could come up with to fix this is:

Wrap around `rsession` (since env vars are wiped when this is launched) and set `HOME=<where you want>` before you call the real `rsession`:

```sh
#!/bin/bash

HOME=${HOME}/path/to/new/.rstudio rsession "$@"
```

Then create an `rsession.conf` file that records where the real home directory is for the session:

```
session-default-working-dir=/users/appl/jnicklas
session-default-new-project-dir=/users/appl/jnicklas
```

Then launch the `rserver` with these new files:

```sh
rserver --www-port 5000 --rsession-config-file ${HOME}/path/to/rsession.conf --rsession-path ${HOME}/path/to/rsession_wrapper.sh
```

It is ugly though.

**Comment by nickjer** [comment]
I recommend we hold off on this until this becomes an actual issue to users.

**Comment by nikolayvoronchikhin** [comment]
Hi @nickjer , we are exploring ways to have users run multiple R sessions in one RStudio Server Open-Source on one machine. Is there a better way than the one you mentioned above?

**Comment by nickjer** [comment]
Hi @nikolayvoronchikhin, unfortunately the problem (which I failed to originally capture) was running multiple RStudio Server (`rserver`) instances for a user concurrently. This allows us to better utilize HPC resources by giving each `rserver` and hence `rsession` process a full compute node with multiple cores for the user. But we had the issue that a user couldn't submit and have more than one `rserver` & `rsession` running concurrently without RStudio Server complaining due to the common workspace shared under the user's home directory. Fortunately, this can be resolved with a bind mount, in particular using containerization tools such as Singularity.

I have not explored the capability of running concurrent `rsession`'s for the same user under a **single** `rserver`. I do not know enough about the internal workings of the reverse proxy code in `rserver` to say if this can be hacked together with the open source version. You could check out:

https://rpubs.com/jmcphers/rstudio-architecture

in particular the "RStudio Server Pro" section for an explanation of how it is done in the pro version. They describe using an `rserver-launcher` process. Maybe after reading the code there is a way to simulate that process?

One solution, which is how [OnDemand](https://osc.github.io/Open-OnDemand/) works is to build a web portal in front (in essence a custom reverse proxy that behaves *like* `rserver`) that launches individual RStudio Server (`rserver`) processes on-demand for a logged in user. And then allows that user to connect to them or stop them when needed. This resolves the *"multiple user `rsessions`'s for a single `rserver`"* issue for open source RStudio Server in a hacky way by just wrapping around `rserver` another reverse proxy that handles authentication and controlling individual `rserver`+`rsession` processes. This allows us to run multiple sessions and with different versions of R using the open source version.

If you want to go that route and keep it simple (not as big as OnDemand) you can explore using Node.js for the custom reverse proxy wrapper as that is what the RStudio Team is using for the Shiny Server:

https://github.com/rstudio/shiny-server

**Comment by beefster** [comment]
I am having this exact issue.  Our nodes share an NFS-mounted home folder, and I am looking for a way to run multiple `rserver` instances without conflicts via the files in ~/.local/share/rstudio since these files are shared across nodes.

I disagree with the design choice to use a hidden directory in the user's home, and especially with the design choice to hardcode it to a system environment variable. I see that it is a beta option to use internal database to store sessions instead, but i'd much rather simply set a scratch path in a conf file or even just as an argument to `rserver` than do an otherwise unnecessary database config.

If I understand correctly, when a user logs into the rstudio-server screen, that is what causes an `rsession` call on their behalf? So if I use @nickjer's trick to wrap the execution in a bash script overriding $HOME, I can adjust what is used for scratch space for the session? I'll give this a try.

**Comment by johrstrom** [comment]
I think `~/.local/share/rstudio` is an XDG environment variable that you could try to change. That is, I believe `~/.local/share` is `$XDG_DATA_HOME`.

**Comment by beefster** [comment]
I realize this is more of a lack of accommodation by rstudio-server itself and this may not be the right repo to post in, but since I'm working on the same exact problem I figure we can help each other.
I couldn't get rsession to respect the XDG_DATA_HOME variable, which needs to be scoped dynamically with $USER and $HOSTNAME, while XDG_CONFIG_HOME needs to stay where it is to keep rstudio-prefs synced across instances. Calling Sys.getenv('XDG_DATA_HOME') shows the string that was set in env-vars but without $USER or $HOSTNAME expanded, not sure if it should, regardless, but the ~/.local/share/rstudio folder still gets made. May have to use the beta database sessions feature, but I would like them to persist through node restarts and sqlite can't live on an NFS filesystem. If I set it to use a central postgres instance i'm not sure if I can differentiate between sessions on different nodes if they're using the same one... might have to spin up separate postgres schemas and configure it in more cli arguments to rserver or a dynamic database.conf file...

Such a simple tweak in functionality is all I need, and the paid Posit version has some launch config capability but I don't want to pay for all of the other features none of which I need
