### ISSUE TITLE
Enable selection of version of R at launch time

### ISSUE THREAD

**Issue by basilgohar** [OSC/bc_osc_rstudio_server#3]
See the following feature request from Shameema:

> I think the option to switch R version will be needed eventually as we don't install every versions of R at /usr/local/. The users can install their own R versions to have the compatibility with the CRAN package of thier interest  and still call the RStudio interface on OnDemand.

This was in response to asking her the question if being able to choose the version of R at launch time would be desired.

**Comment by brianmcmichael** [comment]
Two options have been suggested,

1) Allow the user to select the version prior to launch.
2) Allow the user to select the version in-app via a dropdown.

Option (2) appears to only be available in the paid Pro version. We are using the free open-source version. See: https://support.rstudio.com/hc/en-us/articles/200486138-Using-Different-Versions-of-R

Option (1) is theoretically possible under our architecture, but I have some concerns.
* It would require modifications to https://github.com/AweSim-OSC/vncsim since the pre-app launch interface is provided by that app. I'm thinking it would need a box for users to enter custom variables. A dropdown selection might be ideal, but it's hard to envision how that would work in a way that is app-agnostic.
* RStudio server is quite picky about what versions it will accept. Our system has a module `R/3.3.1` installed, however, it does not work with RStudio Server because it was not compiled with R's shared libraries. Therefore `R/3.3.2` was compiled on the system with the appropriate libraries. So, only one version of R works with this app at this time.
* There are no failure notifications in `vncsim` if the app launch fails R is not properly compiled. I did try running an RStudio instance using the `R/3.3.1` module, and RStudio Server predictably did not load. Since the job is failing in the `xstartup` level and not the app level, there is no error notification provided to the user. (We only track torque errors) Allowing users to initialize this app with their own versions of R would then open the door to all sorts of unpredictable circumstances that we'd need to support.

If multiple versions are a requirement, then our best bet may be to have multiple apps that each use a separate version. We would want each of those apps to launch a blessed version of R that we have confirmed to work. Currently, however, our only option is `R/3.3.2`. Advanced users could launch RStudio Server from the command line using their own versions.

**Comment by nickjer** [comment]
It seems this RStudio Server option looks interesting:

```
  --rsession-which-r arg              path to main R program (e.g. /usr/bin/R)
```

but would need to be explored.

**Comment by nickjer** [comment]
I will add a dropdown where the user can choose the version of R installed on Owens (similar to how we handle Abaqus). In particular I will be adding the new version of R that Shameema installed:

> I have installed Rstudio 1.1.380_server that binds to R/3.4.2.
